# Generated by Django 3.0.1 on 2020-01-01 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_details', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='OrderDetails',
            new_name='OrderDetail',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
