# Generated by Django 3.0.2 on 2020-01-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_details', '0003_auto_20200116_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
