# Generated by Django 3.0.2 on 2020-01-18 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_details', '0004_auto_20200118_1023'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('id', 'phone')},
        ),
    ]
